current_operation: null
deployment_status: initialized
last_updated: '2025-10-30T03:42:23.537662Z'
stacks:
  network-dev:
    environment: dev
    last_updated: '2025-10-30T03:42:23.528069Z'
    stack_name: network
    status: failed
